name: Playwright Tests
on:
  push:
    branches: [gh-actions, master]
  pull_request:
    branches: [gh-actions, master]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.42.1-jammy
    steps:
      - uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Check for package-lock.json
        id: check-lock-file
        run: |
          if [ ! -f ./e2e-tests/package-lock.json ]; then
            echo "::set-output name=exists::false"
          else
            echo "::set-output name=exists::true"
          fi
        working-directory: ./
      - name: Install dependencies (npm ci or npm install)
        run: |
          if [ ${{ steps.check-lock-file.outputs.exists }} == "true" ]; then
            npm ci
          else
            echo "package-lock.json not found, running npm install instead"
            npm install
          fi
        working-directory: ./e2e-tests
      - name: Run your tests
        run: npx playwright test
        working-directory: ./e2e-tests
        env:
          HOME: /root
      #      - name: Get Allure history
      #        uses: actions/checkout@v2
      #        if: always()
      #        continue-on-error: true
      #        with:
      #          ref: gh-pages
      #          path: gh-pages

      - uses: actions/upload-artifact@master
        working-directory: ./e2e-tests
        with:
          name: allure-results
          path: allure-results
          retention-days: 20

      - name: Allure Report with history
        uses: simple-elf/allure-report-action@v1.8
        if: always()
        with:
          allure_results: e2e-tests/allure-results
          gh_pages: gh-pages
          allure_report: e2e-tests/allure-report
          allure_history: e2e-tests/allure-history
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: e2e-tests/allure-history
      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test report'
          state: 'success'
          target_url: https://gustavolira.github.io/backstage-showcase/${{ github.run_number }}
