name: PR Build Image

on:
  pull_request_target:
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.event.pull_request.head.ref }}
  cancel-in-progress: true

env:
  REGISTRY: quay.io

jobs:
  check-image:
    name: Check Image and Relevant Changes
    runs-on: ubuntu-latest
    outputs:
      image_exists: ${{ steps.check-image.outputs.image_exists }}
      relevant_changes: ${{ steps.check-image.outputs.relevant_changes }}
      short_sha: ${{ steps.check-image.outputs.short_sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Image and Relevant Changes
        id: check-image
        uses: ./.github/actions/check-image-and-changes

  build-image:
    name: Build Image
    needs: check-image
    if: ${{ needs.check-image.outputs.relevant_changes == 'true' || needs.check-image.outputs.image_exists == 'false' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Get the latest commits from base branch
        run: |
          git remote add base-origin https://github.com/${{ github.repository }} || true
          git config user.name "${{ github.event.pull_request.user.login }}"
          git config user.email "${{ github.event.pull_request.user.email }}"
          echo "Updating PR with latest commits from ${{ github.event.pull_request.base.ref }} ..."
          git fetch base-origin ${{ github.event.pull_request.base.ref }}
          git merge --no-edit base-origin/${{ github.event.pull_request.base.ref }}

      - name: Build and Push with Buildx
        uses: ./.github/actions/docker-build
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
          imageName: rhdh-community/rhdh
          imageTags: |
            type=ref,prefix=pr-,suffix=-${{ needs.check-image.outputs.short_sha }},event=pr
            type=ref,prefix=pr-,event=pr
          imageLabels: quay.expires-after=14d
          push: true
          platform: linux/amd64

      - name: Comment the image pull link
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'The image is available at:\n* [`quay.io/rhdh-community/rhdh:pr-${{ github.event.number }}`](https://quay.io/rhdh-community/rhdh:pr-${{ github.event.number }}) or\n* [`quay.io/rhdh-community/rhdh:pr-${{ github.event.number }}-${{ needs.check-image.outputs.short_sha }}`](https://quay.io/rhdh-community/rhdh:pr-${{ github.event.number }}-${{ needs.check-image.outputs.short_sha }})'
            })

  skip-build:
    name: Skip Build Notification
    needs: check-image
    if: ${{ needs.check-image.outputs.relevant_changes == 'false' && needs.check-image.outputs.image_exists == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Skip build notification
        run: |
          echo "::notice::Skipping build: Image already exists and no relevant changes detected."
